-- init.sql
-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- init.sql
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fitness_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness_tracker` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `fitness_tracker`;

-- Create a dedicated user for your backend with consistent password
CREATE USER IF NOT EXISTS 'ft_appuser'@'%' IDENTIFIED BY 'StrongPassword123!';
GRANT ALL PRIVILEGES ON fitness_tracker.* TO 'ft_appuser'@'%';
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `gender` ENUM('male', 'female', 'other') NULL DEFAULT NULL,
  `height_cm` DECIMAL(5,2) NULL DEFAULT NULL,
  `weight_kg` DECIMAL(5,2) NULL DEFAULT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `country` VARCHAR(100) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `idx_user_email` (`email` ASC) VISIBLE
)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `activity_type` VARCHAR(50) NOT NULL,
  `duration` INT NOT NULL,
  `intensity` ENUM('low', 'medium', 'high') NULL DEFAULT NULL,
  `calories_burned` INT NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_activities_user_date` (`user_id` ASC, `date` ASC) VISIBLE,
  CONSTRAINT `activities_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`aiprompts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`aiprompts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prompt_type` VARCHAR(50) NOT NULL,
  `prompt_template` TEXT NOT NULL,
  `variables` JSON NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `aiprompts_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `fitness_tracker`.`users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`recommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS recommendations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  goal_type VARCHAR(50) NOT NULL,
  target_value DECIMAL(5,2) NOT NULL,
  deadline DATE NOT NULL,
  recommended_calories INT,
  recommended_protein VARCHAR(20),
  recommended_carbs VARCHAR(20),
  recommended_fats VARCHAR(20),
  meal_plan JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- -----------------------------------------------------
-- Table `fitness_tracker`.`workouttemplates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`workouttemplates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `difficulty_level` ENUM('beginner', 'intermediate', 'advanced') NULL DEFAULT NULL,
  `estimated_duration` INT NULL DEFAULT NULL,
  `equipment_needed` JSON NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `workouttemplates_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `fitness_tracker`.`users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`completedworkouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`completedworkouts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `template_id` INT NULL DEFAULT NULL,
  `workout_date` DATE NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `calories_burned` INT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `template_id` (`template_id` ASC) VISIBLE,
  INDEX `idx_completed_workouts_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `completedworkouts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `completedworkouts_ibfk_2`
    FOREIGN KEY (`template_id`)
    REFERENCES `fitness_tracker`.`workouttemplates` (`id`)
    ON DELETE SET NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`exercisecategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`exercisecategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `exercisecategories_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `fitness_tracker`.`users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  `difficulty_level` ENUM('beginner', 'intermediate', 'advanced') NULL DEFAULT NULL,
  `muscle_groups` JSON NULL DEFAULT NULL,
  `equipment_needed` JSON NULL DEFAULT NULL,
  `instructions` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `exercises_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `fitness_tracker`.`exercisecategories` (`id`),
  CONSTRAINT `exercises_ibfk_2`
    FOREIGN KEY (`created_by`)
    REFERENCES `fitness_tracker`.`users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`completedworkouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`completedworkouts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `template_id` INT NULL DEFAULT NULL,
  `workout_date` DATE NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `calories_burned` INT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `template_id` (`template_id` ASC) VISIBLE,
  INDEX `idx_completed_workouts_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `completedworkouts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `completedworkouts_ibfk_2`
    FOREIGN KEY (`template_id`)
    REFERENCES `fitness_tracker`.`workouttemplates` (`id`)
    ON DELETE SET NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`completedworkoutexercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`completedworkoutexercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `completed_workout_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets_completed` INT NULL DEFAULT NULL,
  `reps_completed` INT NULL DEFAULT NULL,
  `weight_used` DECIMAL(5,2) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `completed_workout_id` (`completed_workout_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `completedworkoutexercises_ibfk_1`
    FOREIGN KEY (`completed_workout_id`)
    REFERENCES `fitness_tracker`.`completedworkouts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `completedworkoutexercises_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `fitness_tracker`.`exercises` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

/* ------------------------------------------------------------------
   Table: fitness_tracker.messages
   ------------------------------------------------------------------*/
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`messages` (
  `message_id`   INT             NOT NULL AUTO_INCREMENT,
  `user_id`      INT             NOT NULL,
  `subject`      VARCHAR(255)         NULL,
  `body`         TEXT            NOT NULL,
  `admin_reply`  TEXT                NULL,          -- ← added for admin responses
  `status`       ENUM('open','closed') DEFAULT 'open',
  `is_read`      BOOLEAN          DEFAULT FALSE,
  `created_at`   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`),

  /* helpful for filtering by user in queries */
  KEY `idx_messages_user` (`user_id`),

  /* FK now matches the actual PK column name in users (id) */
  CONSTRAINT `messages_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE       = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`goals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `goal_type` ENUM('lose_weight', 'gain_muscle', 'add_weight', 'custom') NOT NULL,
  `target_value` DECIMAL(5,2) NULL DEFAULT NULL,
  `current_value` DECIMAL(5,2) NULL DEFAULT NULL,
  `status` ENUM('in_progress', 'completed', 'abandoned') NULL DEFAULT 'in_progress',
  `deadline` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_goals_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `goals_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`healthmetrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`healthmetrics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `weight_kg` DECIMAL(5,2) NULL DEFAULT NULL,
  `body_fat_percentage` DECIMAL(5,2) NULL DEFAULT NULL,
  `muscle_mass_kg` DECIMAL(5,2) NULL DEFAULT NULL,
  `height_cm` DECIMAL(5,2) NULL DEFAULT NULL,
  `recorded_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `healthmetrics_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`nutrition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`nutrition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `meal_type` VARCHAR(50) NULL DEFAULT NULL,
  `calories` INT NULL DEFAULT NULL,
  `protein` DECIMAL(5,2) NULL DEFAULT NULL,
  `carbs` DECIMAL(5,2) NULL DEFAULT NULL,
  `fats` DECIMAL(5,2) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_nutrition_user_date` (`user_id` ASC, `date` ASC) VISIBLE,
  CONSTRAINT `nutrition_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `goal_id` INT NULL DEFAULT NULL,
  `recorded_value` DECIMAL(5,2) NOT NULL,
  `measurement_type` VARCHAR(50) NOT NULL,
  `recorded_date` DATE NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `goal_id` (`goal_id` ASC),
  INDEX `idx_progress_user` (`user_id` ASC),
  CONSTRAINT `progress_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `progress_ibfk_2`
    FOREIGN KEY (`goal_id`)
    REFERENCES `fitness_tracker`.`goals` (`id`)
    ON DELETE SET NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`usercredentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`usercredentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `provider_user_id` VARCHAR(255) NOT NULL,
  `access_token` TEXT NULL DEFAULT NULL,
  `refresh_token` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_provider_user` (`provider` ASC, `provider_user_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `usercredentials_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`usersettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`usersettings` (
  `user_id` INT NOT NULL,
  `notification_preferences` JSON NULL DEFAULT NULL,
  `privacy_settings` JSON NULL DEFAULT NULL,
  `theme_preferences` JSON NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `usersettings_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fitness_tracker`.`users` (`id`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`workouttemplateexercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`workouttemplateexercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `sets` INT NOT NULL,
  `reps` INT NOT NULL,
  `rest_time` INT NULL DEFAULT NULL,
  `sequence_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `template_id` (`template_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `workouttemplateexercises_ibfk_1`
    FOREIGN KEY (`template_id`)
    REFERENCES `fitness_tracker`.`workouttemplates` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `workouttemplateexercises_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `fitness_tracker`.`exercises` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `fitness_tracker`.`completedexercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_tracker`.`completedexercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `duration_minutes` INT DEFAULT 20,
  `calories_burned` INT DEFAULT 100,
  `completed_on` DATE NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `fitness_tracker`.`users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`exercise_id`) REFERENCES `fitness_tracker`.`exercises` (`id`) ON DELETE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- Dummy Data

-- Users
INSERT INTO users (id, first_name, last_name, email, password_hash, date_of_birth, height_cm, weight_kg, is_admin)
VALUES
  (1, 'Admin', 'User', 'admin@mavs.uta.edu', 'admin@123', '2000-12-12', 169, 69, 1),
  (2, 'Test', 'User', 'user@mavs.uta.edu', 'user@123', '1998-09-07', 167.6, 72.3, 0);

-- Exercise Categories
INSERT INTO exercisecategories (name, created_by)
VALUES
  ('Strength', 1),
  ('Cardio', 1),
  ('Core', 1),
  ('Flexibility', 1);

-- Exercises
INSERT INTO exercises (name, category_id, difficulty_level, created_by)
VALUES
  ('Push Ups', 1, 'beginner', 1),
  ('Squats', 1, 'beginner', 1),
  ('Jumping Jacks', 2, 'beginner', 1),
  ('Lunges', 1, 'intermediate', 1),
  ('Plank', 3, 'intermediate', 1),
  ('Burpees', 2, 'advanced', 1),
  ('Mountain Climbers', 2, 'advanced', 1);

-- Workout Templates
INSERT INTO workouttemplates (name, description, difficulty_level, estimated_duration, created_by)
VALUES
  ('Full Body Blast', 'A high-intensity full-body workout.', 'intermediate', 45, 1),
  ('Beginner Cardio', 'Light cardio session.', 'beginner', 20, 1),
  ('Cardio Burnout', 'High-intensity cardio routine.', 'advanced', 30, 1),
  ('Strength Builder', 'Intermediate strength training session.', 'intermediate', 40, 1),
  ('Core Focus', 'Plank-based core exercises.', 'beginner', 20, 1),
  ('Leg Day Special', 'Targeted lower body workout.', 'intermediate', 35, 1),
  ('Quick Sweat', 'Short burst workout for busy days.', 'beginner', 15, 1);

-- Workout Template Exercises
INSERT INTO workouttemplateexercises (template_id, exercise_id, sets, reps, rest_time, sequence_order)
VALUES
  (1, 1, 3, 12, 60, 1),  -- Full Body Blast: Push Ups
  (1, 2, 3, 10, 45, 2),  -- Full Body Blast: Squats
  (3, 3, 3, 20, 30, 1),  -- Cardio Burnout: Jumping Jacks
  (3, 6, 3, 10, 45, 2),  -- Cardio Burnout: Burpees
  (4, 2, 3, 12, 60, 1),  -- Strength Builder: Squats
  (4, 4, 3, 10, 45, 2),  -- Strength Builder: Lunges
  (5, 5, 3, 30, 60, 1),  -- Core Focus: Plank
  (6, 2, 3, 15, 45, 1),  -- Leg Day Special: Squats
  (6, 4, 3, 10, 45, 2),  -- Leg Day Special: Lunges
  (7, 3, 2, 20, 30, 1);  -- Quick Sweat: Jumping Jacks


-- Activities for Test User (id 2)
INSERT INTO activities (user_id, activity_type, duration, intensity, calories_burned, date, notes)
VALUES
  (2, 'Running', 30, 'high', 300, '2025-04-25', 'Evening jog'),
  (2, 'Cycling', 45, 'medium', 400, '2025-04-24', 'Morning cycling'),
  (2, 'Swimming', 40, 'high', 500, '2025-04-23', 'Swimming laps'),
  (2, 'Strength Training', 50, 'high', 450, '2025-04-25', 'Upper body workout'),
  (2, 'Yoga', 60, 'low', 200, '2025-04-26', 'Relaxing evening yoga'),
  (2, 'Running', 35, 'high', 350, '2025-04-27', 'Morning sprint session');

-- Nutrition for Test User (id 2)
INSERT INTO nutrition (user_id, date, meal_type, calories, protein, carbs, fats, notes)
VALUES
  (2, '2025-04-25', 'Breakfast', 350, 20.0, 40.0, 12.0, 'Oatmeal and protein'),
  (2, '2025-04-25', 'Lunch', 600, 35.0, 70.0, 15.0, 'Chicken and rice'),
  (2, '2025-04-25', 'Dinner', 550, 30.0, 50.0, 20.0, 'Fish and veggies'),
  (2, '2025-04-26', 'Breakfast', 400, 25.0, 50.0, 15.0, 'Protein pancakes'),
  (2, '2025-04-26', 'Lunch', 700, 40.0, 80.0, 20.0, 'Grilled salmon with veggies'),
  (2, '2025-04-26', 'Dinner', 600, 35.0, 60.0, 18.0, 'Turkey wrap with salad');

-- Goals for Test User (id 2)
INSERT INTO goals (user_id, goal_type, target_value, current_value, status, deadline)
VALUES
  (2, 'lose_weight', 70.00, 75.00, 'in_progress', '2025-06-01'),
  (2, 'gain_muscle', 80.00, 75.00, 'in_progress', '2025-09-01');

-- Progress for Test User (id 2)
INSERT INTO progress (user_id, goal_id, recorded_value, measurement_type, recorded_date, notes)
VALUES
  (2, 1, 74.0, 'weight', '2025-04-25', 'Good progress!'),
  (2, 1, 73.5, 'weight', '2025-04-26', 'Getting closer to goal.'),
  (2, 1, 73.0, 'weight', '2025-04-27', 'Weight dropping well.'),
  (2, 2, 76.5, 'muscle_mass', '2025-04-27', 'Good muscle development');

-- Completed Workouts for Test User (id 2)
INSERT INTO completedworkouts (user_id, template_id, workout_date, duration, calories_burned, notes)
VALUES
  (2, 1, '2025-04-25', 45, 400, 'Completed Full Body Blast!'),
  (2, 2, '2025-04-26', 20, 250, 'Completed Beginner Cardio!'),
  (2, 3, '2025-04-27', 30, 350, 'Completed Cardio Burnout!');

-- Completed Workout Exercises for Test User (id 2)
INSERT INTO completedworkoutexercises (completed_workout_id, exercise_id, sets_completed, reps_completed, weight_used, notes)
VALUES
  (1, 1, 3, 12, 0, 'Push-Ups completed'),
  (1, 2, 3, 10, 0, 'Squats completed'),
  (2, 3, 3, 30, 0, 'Jumping Jacks complete'),
  (2, 6, 3, 10, 0, 'Burpees complete'),
  (3, 3, 3, 25, 0, 'Jumping Jacks Cardio set complete'),
  (3, 7, 3, 15, 0, 'Mountain Climbers complete');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
